apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravipp01
spec:
  selector:
    matchLabels:
      app: raviapp01
  template:
    metadata:
      labels:
        app: raviapp01
    spec:
      containers:
      - name: raviapp01
        image: psacr02.azurecr.io/raviapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
